"""empty message

Revision ID: 01f5717c16b0
Revises: 61c2e9b07e82
Create Date: 2020-08-31 17:23:42.244454

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '01f5717c16b0'
down_revision = '61c2e9b07e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RANO',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('type', sa.String(length=128), nullable=False),
                    sa.Column('site', sa.String(length=128), nullable=False),
                    sa.Column('uri', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('RANO_CREDENTIALS',
                    sa.Column('rano_id', sa.Integer(), nullable=False),
                    sa.Column('host', sa.String(length=128), nullable=False),
                    sa.Column('project', sa.String(length=128), nullable=False),
                    sa.Column('user', sa.String(length=128), nullable=False),
                    sa.Column('password', sa.String(length=128), nullable=False),
                    sa.ForeignKeyConstraint(['rano_id'], ['RANO.id'], ),
                    sa.PrimaryKeyConstraint('rano_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RANO_CREDENTIALS')
    op.drop_table('RANO')
    # ### end Alembic commands ###
