"""empty message

Revision ID: 3415a296d2ef
Revises: 
Create Date: 2019-11-03 20:10:38.459033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3415a296d2ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NFVO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('site', sa.String(length=128), nullable=False),
    sa.Column('uri', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NFVO_CREDENTIALS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('project', sa.String(length=128), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['NFVO.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NFVO_CREDENTIALS')
    op.drop_table('NFVO')
    # ### end Alembic commands ###
