"""empty message

Revision ID: ba9b9fa9fe6a
Revises: 3415a296d2ef
Create Date: 2019-12-06 11:14:47.115843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9b9fa9fe6a'
down_revision = '3415a296d2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('NFVO_CREDENTIALS', 'id', new_column_name='nfvo_id')
    #op.drop_constraint(None, 'NFVO_CREDENTIALS', type_='foreignkey')
    #op.create_foreign_key(None, 'NFVO_CREDENTIALS', 'NFVO', ['nfvo_id'], ['id'])
    #op.drop_column('NFVO_CREDENTIALS', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NFVO_CREDENTIALS', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'NFVO_CREDENTIALS', type_='foreignkey')
    op.create_foreign_key(None, 'NFVO_CREDENTIALS', 'NFVO', ['id'], ['id'])
    # ### end Alembic commands ###
