version: '3.1'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - al-network
    ports:
      - 80:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: adaptation-layer
    networks:
      al-network:
        aliases:
          - flask-app 
    ports:
      - 5000:5000
networks:
    al-network:
