version: '3.1'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - 80:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: adaptation-layer
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
          - flask-app
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
networks:
    my-network:
