name: Build and push Docker images

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # temporary push on a test dockerhub repo
          repository: zvfvrv/mso-lo
          tag_with_ref: true
          tags: latest
          target: prod
